### ISSUE TITLE
VSIX file should be published as release on GitHub

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-project-initializer#34] opened 2019-05-10 07:32 UTC
Che registry needs VSIX files and we should publish VSIX file on GitHub as release as VSCode marketplace as rate limits

**Comment by nickboldt** [comment] 2019-12-06 23:01
Resolving as a dupe of #40 which provides greater context for the reason we need to publish on GH.

See also https://github.com/eclipse/che/issues/14573

**Closed by nickboldt** 2019-12-06 23:01 UTC
